### ISSUE TITLE
Composer Install

### ISSUE THREAD

**Issue by parkerj** [sbuberl/fSQL#14]
How do you install this via composer? I've tried `composer require sbuberl/fSQL` as well as `composer require fsql/fsql` and neither works.

**Comment by sbuberl** [comment]
Hello,

Thanks for reporting for this.  Seems an issue with my composer.  I'n looking into now and will report back once it's fixed.

Thanks.

**Comment by sbuberl** [comment]
I was having issues trying to get require to work with locally installed package, because this was not on Packagist.  So I submitted it there:
https://packagist.org/packages/sbuberl/fsql

Also, master is not 100% stable and error free, you''ll need to add this to your composer.json so it can be used:
"minimum-stability": "dev"

After that:
composer require sbuberl/fSQL
should be work fine.

**Comment by parkerj** [comment]
Ok, thanks.
